### PR TITLE
Handle SIGSEGV by restarting streaming process

### LINKED ISSUE #32: Streaming fails without restart
We run the docker image provided from this repo on an AXIS P1467-LE Bullet Camera. The streaming works as expected. But after few hours of streaming the following error occurs:

```
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 8' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```

The process is not restarted and the streaming stops.

It would be nice, that the process just exits and it is restarted by Docker automatically.

### PR DESCRIPTION
**Pull request by david-molnar-oculai**
### Describe your changes

When SIGSEGV error happens in GStreamer, it tries to run the debugger by default. This then fails, since the debugger is not installed and as a result, the process is not restarted, just keeps hanging. The streaming the stops.

The PR disables the default debugger and let's the process die. Then it is restarted by Docker.

Sample SIGSEGV error:
```
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 8' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```

### Issue ticket number and link

- Fixes #32

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: start_stream.sh [hunk 1]
```diff
@@ -1,4 +1,4 @@
 #!/bin/bash
-gst-launch-1.0 rtspsrc \
+gst-launch-1.0 --no-fault rtspsrc \
```
Comment (david-molnar-oculai) [inline start_stream.sh:2]: Based on https://stackoverflow.com/a/75843160/1093508.

**Review by bsriramprasad — APPROVED** [review]
apologies for the delayed response and thank you for the contribution, we accept the change and will soon be pulled in to the main.
